### PR TITLE
Added support to save to and load from a file in raw or json formats.

### PR DESCRIPTION
**Pull request by gravesjohnr**
Peter,

This is the kind of thing I was requesting.  No worries if you want to keep it just raw cut/paste.

I thought this would be easier for save/load and with JSON format for those who like to keep in source control.

I used https://github.com/eligrey/FileSaver.js to allow for multi-browser support.

### CODE REVIEW

**Comment by petersirka** [comment]
Great! I'll update a bit code, but the functionality is OK!

**Comment by gravesjohnr** [comment]
Thanks!  I like the formatting changes you made.  I guess you didn't like the JSON format button.  No worries.  It is easy enough to go back and forth.

Very glad I could contribute a bit.  I'll eventually get the alexa component done.

**Comment by petersirka** [comment]
I have removed `json` because I didn't see any benefits. More choices are more problems and the current mechanism is good and sufficient I think. Or did you have some plans with plain JSON format?

**Comment by petersirka** [comment]
BTW: I have added you as a contributor, is it ok for you? You know, GPPR :-D

**Comment by gravesjohnr** [comment]
The JSON format is easier to manage in a code management system.  It allows me to see what has changed from version to version.  Its easy enough to convert it outside the tool.  Thank you for keeping the JSON input option!

**Comment by gravesjohnr** [comment]
BTW, I completely agree, "More choices are more problems"!!!

**Pull request merged**
