### PR TITLE
Added an option to enable self-debug in each component

### PR DESCRIPTION
**Pull request by khaledkhalil94**
Small change but will definitely make using Flow easier.
With this new option, users can enable debug in any component and log the data before it is sent out of the component.

### CODE REVIEW

**Comment by petersirka** [comment]
@molda what do you think about it?

**Comment by molda** [comment]
I like it.

**Comment by petersirka** [comment]
I'm going to update code a bit.

**Comment by petersirka** [comment]
Hi @khaledkhalil94,
thank you very much. I have updated a bit your code. You can test it. Again: THANK YOU.

**Pull request merged**
