### PR TITLE
Added tooltip support.

### PR DESCRIPTION
**Pull request by gravesjohnr**
In the input or output settings, use the following syntax:
exports.input = ['color|tip'];
e.g. (First input has default colour, with tip 'Counter'.  Second has an RGB colour with tip 'Reset'. Third has no
tooltip, but is colour red.)
exports.input = ['|Counter', '#ff5555|Reset', 'red'];

### CODE REVIEW

**Comment by gravesjohnr** [comment]
I had issues with the .css.  I was unable to override the values of .ui-tooltip.  I'm not sure why.  So the black background is pretty ugly and the font is a bit small.

Demo: https://youtu.be/_kZUE3xUUd0

**Comment by petersirka** [comment]
Thank you! For future updates please follow our: <https://github.com/totaljs/guidelines>. I'm going to update it.

**Comment by gravesjohnr** [comment]
Sorry.  I thought I did.  What was I missing?  I often miss the single ' vs the double ".

**Comment by petersirka** [comment]
It was OK, only small faults were there.

**Comment by gravesjohnr** [comment]
Wow.  I like how you used svg rather than then j-tooltip.  Much cleaner.  Thanks!

**Pull request merged**
